name: Daily Runner

on:
  # Scheduled run at 9:00 AM IST (3:30 AM UTC)
  schedule:
    - cron: "30 3 * * *"
  # Enable manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run runner.py
        run: python runner.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}
